name: "ci"

on: [push, pull_request]

jobs:
  ci:
    name: "ci"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - uses: cachix/cachix-action@v10
      with:
        name: ninegua
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-shell --run 'make -C test'
